#!/bin/sh

if test "$DBUS_SESSION_BUS_ADDRESS" = ""; then
  eval "$(dbus-launch --exit-with-session --sh-syntax)"
fi
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
  dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# https://www.iodocs.com/how-to-enable-gpu-fan-settings-nvidia-in-linux/
nvidia-settings -a '[gpu:0]/GPUFanControlState=1' -a '[fan:0]/GPUTargetFanSpeed=40' --load-config-only

numlockx
xset r rate 200 50
imwheel -b 45 &

unclutter --timeout 2 & # not work as a service, WantedBy graphical-session.target
dwm-status ~/.dwm-status.toml &

# Timers
systemctl restart wallpaper.service & # ../../modules/system/boot/timers/wallpaper.nix
# slstatus & # ../../modules/system/boot/timers/slstatus.nix

systemctl --user restart dunst.service & # ../services/dunst.nix
sxhkd &                                  # ../services/sxhkd.nix not work as a service unit, but makes config
# taskwarrior

systemctl --user restart redshift.service & # ../../modules/services/x11/redshift.nix

# XDG_SESSION_TYPE=x11 remote-touchpad -bind :9000 -secret pc &
# wetty -b / -p 9999 &

session=${1:-dwm}

case $session in
  i3 | i3wm) exec i3 ;;
  kde) exec startplasma-x11 ;;
  xfce | xfce4) exec startxfce4 ;;
  dwm) exec dwm ;;
  # Xephyr :0 -ac -br -noreset -screen 1152x720 & DISPLAY=:0.1 startx $XINITRC awesome
  awesome) exec awesome -c /etc/nixos/vim/lua/awesome_rc.lua ;;

  *) exec "$1" ;;
esac
