{pkgs, ...}: {
  imports = [./LF_ICONS.nix];

  environment.variables = {
    TERMINAL = "alacritty";
    EDITOR = "nvim";
    editor = "vim";
    MANPAGER = "sh -c 'col -bx | bat -l man -p'";
    PNPM_HOME = "$HOME/.pnpm-global";
    NPM_CONFIG_PREFIX = "$HOME/.node_modules";
    # NODE_OPTIONS = "--loader ts-node/esm --experimental-specifier-resolution=node --no-warnings";
    NODE_OPTIONS = "--no-warnings";
    PRISMA_QUERY_ENGINE_LIBRARY = "${pkgs.prisma-engines}/lib/libquery_engine.node";
    PRISMA_QUERY_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/query-engine";
    PRISMA_MIGRATION_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/migration-engine";
    PRISMA_INTROSPECTION_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/introspection-engine";
    PRISMA_FMT_BINARY = "${pkgs.prisma-engines}/bin/prisma-fmt";
    GDK_SCALE = "1";
    GDK_DPI_SCALE = "1";
    QT_AUTO_SCREEN_SET_FACTOR = "0";
    QT_SCALE_FACTOR = "1";
    QT_FONT_DPI = "144";
  };
  environment.shellAliases = {
    nf = "";
    puppeteer = "puppeteer --no-sandbox";
    mmdc = "mmdc -p /etc/nixos/puppeteerConfigFile.json";
    brave = "brave --no-sandbox --enable-features=TouchpadOverscrollHistoryNavigation";
    wol_pc = "wol b4:2e:99:61:09:cf";
    ".." = "cd ..";
    "..." = "../..";
    "colored-tree" = "${pkgs.tree}/bin/tree -C";
    bp = "bat package.json";
    da = "direnv allow";
    dr = "direnv reload";
    l = "ls -l --group-directories-first";
    la = "ls -la";
    lg = "lazygit";
    ls = "exa --icons --git";
    lt = "ls --tree --level=2";
    lt3 = "ls --tree --level=3";
    mc = "tmux split -h lf; lf";
    mcd = "tmux split -h nd; ndcw; ndtw";
    nu = "npm run update";
    ni = "npm install";
    nd = "npm run dev";
    ndh = "npm run dev -- --host";
    ndo = "npm run dev -- --open";
    npa = "npm run pa";
    nrpc = "npm run codegen";
    nrb = "npm run build";
    nrd = "npm run deploy";
    nrc = "npm run check";
    nrcw = "npm run check:watch";
    nrp = "npm run preview";
    nrpo = "npm run preview -- --open";
    nrpr = "npm run prepare";
    nrr = "npm run run";
    nrs = "npm run start";
    nrt = "npm run test";
    nrtd = "npm run test:dev";
    nrtu = "npm run test:unit";
    nrtw = "npm run test:watch";
    nsb = "npm run storybook";
    oras = "curl wttr.in/Vilnius";
    pdp = "prisma db push";
    pdr = "prisma db push --accept-data-loss --force-reset";
    pds = "prisma db seed";
    pg = "prisma generate";
    pn = "pnpm";
    tre = "trans :en";
    trl = "trans :lt";
    up = "nixos-rebuild switch";
    uph = "nixos-rebuild switch && /etc/nixos/post-build-hook.sh";
    upb = "nixos-rebuild build";
    upt = "nixos-rebuild test";
    x = "startx";
  };
}
