#!/usr/bin/env zsh
# shellcheck shell=zsh

alias sway="sway > /var/log/sway.log 2>&1"
alias sway_="sway > /var/log/sway.log 2>&1"

export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
export NIX_PACKAGE_SEARCH_EXPERIMENTAL=true
export YDIFF_OPTIONS='-w40'

# FPATH
setopt extended_glob
fpath=(/etc/nixos/sh $fpath)
autoload -Uz $fpath[1]/**/*(.:t)

# PATH
typeset -TU PATH path ':'
# path+=( /etc/nixos/*(N-/) )
path+=(${0:a:h}/bin)

# CPATH
typeset -TU CPATH cpath ':'
cpath+=('/run/current-system/sw/include/' '/root/include/')

typeset -TU VST3_PATH vst3path ':'
vst3path+=('/etc/nixos/audio/vst3')
export vst3path

# etc..
typeset -TU NIX_PROFILES np ' '
typeset -TU GTK_PATH gtk_path ':'
typeset -TU XCURSOR_PATH xcursor_path ':'

source $SELF/sh/zsh.completion
source $SELF/sh/zsh.hooks
source $SELF/sh/zshrc.dev

nix-clean() {
	nix-env --delete-generations old
	nix-store --gc
	nix-channel --update
	nix-env -u --always
	for link in /nix/var/nix/gcroots/auto/*; do
		rm $(readlink "$link")
	done
	nix-collect-garbage -d
}

# source /etc/nixos/sh/zsh.alias
