" vim: ft=vim
" https://devhints.io/vimscript
packadd! editorconfig

let g:which_key_vertical = 1
let g:AutoPairsFlyMode = 0
let g:AutoPairsShortcutBackInsert = ''
let g:netrw_banner=0
let g:netrw_liststyle=3
let g:netrw_winsize=-30
let g:netrw_wiw=0

source $XDG_CONFIG_HOME/vim/functions.vim
source $XDG_CONFIG_HOME/vim/shared.vim
source $XDG_CONFIG_HOME/vim/keymaps.vim
source $XDG_CONFIG_HOME/vim/switch.vim

