#!/bin/sh

# export GDK_DPI_SCALE="0.35"
# export GDK_SCALE="2"

xcompmgr &
devilspie2 -a &
numlockx
xset r rate 250 50
sxhkd &
systemctl --user restart dunst.service &
systemctl --user restart wallpaper.service &
systemctl --user restart unclutter-xfixes.service &
systemctl --user restart dwm-status.service &
# xrandr_dpi &

if test -z "$DBUS_SESSION_BUS_ADDRESS" = ""; then
	eval "$(dbus-launch --exit-with-session --sh-syntax)"
fi
systemctl --user import-environment DISPLAY XAUTHORITY XDG_SESSION_ID

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
	dbus-update-activation-environment DISPLAY XAUTHORITY
fi

if [ "$(hostname)" = pc ]; then
	xset s 3600 3600
	xset dpms 3600 3600 3600
	nvidia-settings -a '[gpu:0]/GPUFanControlState=1' -a '[fan:0]/GPUTargetFanSpeed=40' --load-config-only
	XDG_SESSION_TYPE=x11 remote-touchpad -bind :9000 -secret pc &
	systemctl --user start imwheel.service &
	deskflow-client -f --debug INFO --name pc --enable-crypto --sync-language dell:24800 &
elif [ "$(hostname)" = dell ]; then
	deskflow-server -f --debug INFO --name dell --enable-crypto --address :24800 -c /etc/nixos/deskflow-dell/deskflow-server.conf --tls-cert /etc/nixos/deskflow-dell/tls/deskflow.pem &
	systemctl --user restart redshift.service &
fi

session=${1:-dwm}
case $session in
dwm)
	exec dwm
	;;
awesome | a)
	exec awesome
	;;
i3 | i3wm)
	exec i3
	;;
kde)
	exec startplasma-x11
	;;
xfce | xfce4)
	exec startxfce4
	;;
*)
	exec "$1"
	;;
esac
