# vim: ft=sh

# XNOTIFY_FIFO="$HOME/.cache/xnotify$DISPLAY.fifo"
# export XNOTIFY_FIFO
# rm -f $XNOTIFY_FIFO
# mkfifo $XNOTIFY_FIFO
# xnotify 0<>$XNOTIFY_FIFO

export XCURSOR_THEME=XCursor-Pro-Light
export XCURSOR_SIZE=64

# https://unix.stackexchange.com/questions/596887/how-to-scale-the-resolution-display-of-the-desktop-and-or-applications
# export QT_QPA_PLATFORMTHEME=gtk2
# export QT_STYLE_OVERRIDE=kvantum
export QT_AUTO_SCREEN_SET_FACTOR=0
export QT_SCALE_FACTOR=2
export QT_FONT_DPI=96

# export GTK_USE_PORTAL=1
# export GDK_SCALE="2"
# export GTK2_RC_FILES=/etc/nixos/x11/gtk2/gtkrc

export GDK_DPI_SCALE="0.75"
export GTK_THEME=Adwaita:dark
export NVIM_REMOTE=~/.cache/nvim/server.pipe
export EDITOR="nvim --server $NVIM_REMOTE"

# https://nixos.org/manual/nixos/stable/#sec-x11
systemctl --user import-environment DISPLAY XDG_SESSION_ID
systemctl --user start nixos-fake-graphical-session.target
dbus-daemon --session --address="unix:path=/run/user/$(id -u)/bus" &

xrdb $HOME/.Xresources
numlockx on
xset r rate 250 50
sxhkd &

# xcompmgr &
# picom -b &
# xrandr_dpi
# devilspie2 -a

if [ "$(hostname)" = pc ]; then
	xset s 3600 3600 # xset dpms3600 3600 3600
	nvidia-settings -a '[gpu:0]/GPUFanControlState=1' -a '[fan:0]/GPUTargetFanSpeed=40' --load-config-only
elif [ "$(hostname)" = dell ]; then
	systemctl --user start redshift.service &
fi

systemctl --user start wallpaper.service &
systemctl --user start unclutter-xfixes.service &
systemctl --user start dunst.service &
systemctl --user start dwm-status.service &

session=${1:-dwm}
case $session in
dwm)
	# exec dwmloopsimple
	exec dwm
	;;
*)
	exec "$1"
	;;
esac
