#!/usr/bin/env bash

HOST=aldale.lt
PASS='tfJRqf0aV&f(pKLm'
USER=Edvinas
FTPURL="ftp://$USER:$PASS@$HOST"
LCD=$(dirname "$0")
RCD=/domains/aldale.lt/public_html

DELETE="--delete"

lftp -c "set ftp:list-options -a;
set cmd:fail-exit yes;
# set ssl:verify-certificate false;
open '$FTPURL';
lcd $LCD;
cd $RCD;
mirror --reverse \
$DELETE \
--verbose \
--exclude-glob .git/ \
--exclude-glob __pycache__/ \
--exclude-glob vendor/phpunit/ \
"
