[global]
invalid users=foo
passwd program=/run/wrappers/bin/passwd %u
security=USER
# workgroup=root
server string=smbnix
netbios name=smbnix
hosts allow=192.168.1. 127.0.0.1 localhost
hosts deny=0.0.0.0/0
guest account=nobody

[public]
path=/mnt/Shares/Public
browsable=yes
read only=no
guest ok=yes
create mask=0644
directory mask=0755
force user=root
# force group=root

