wkr({
  name = 'GOTO',
  h = { Go.homepage.cword, 'nixpkgs#<cword>.meta.homepage' },
  H = { Go.homepage.cWORD, 'nixpkgs#<cWORD>.meta.homepage' },
  l = { Go.luajitPackages.cword, 'luajitPackages.<cword>.meta.homepage' },
  L = { Go.luajitPackages.cWORD, 'luajitPackages.<cWORD>.meta.homepage' },
  p = { Go.python3Packages.cword, 'python3Packages.<cword>.meta.homepage' },
  P = { Go.python3Packages.cWORD, 'python3Packages.<cWORD>.meta.homepage' },
  n = { Go.nodePackages.cword, 'nodePackages.<cword>.meta.homepage' },
  N = { Go.nodePackages.cWORD, 'nodePackages.<cWORD>.meta.homepage' },
  v = { Go.vimPlugins.cword, 'vimPlugins.<cword>.meta.homepage' },
  V = { Go.vimPlugins.cWORD, 'vimPlugins.<cWORD>.meta.homepage' },
  x = { Go.xopen.cfile, '!xdg-open <cfile>' },
  m = { Go.mynixos.cword, 'mynixos.org <cword>' },
  M = { Go.mynixos.cWORD, 'mynixos.org <cWORD>' },
  s = { Go.github.source, 'github.source' },
  g = { GoGithub, 'github:owner/repo' },
}, { prefix = '<leader>g' })
