# vim: cms=#\ %s
# /etc/profiles/per-user/root/share/doc/mpv/mpv.conf
# vo=gpu-next
# gpu-api=vulkan
# hwdec=vulkan
# gpu-context=waylandvk
# hwdec-codecs=all
# fs=no
volume-max=100
volume=80



osc=no
border=no
# keep-open=yes
# keepaspect-window=no

[Idle]
profile-cond=p["idle-active"]
profile-restore=copy-equal
title=' '
keepaspect=no
background=none
