# vim: cms=#\ %s
# /etc/profiles/per-user/root/share/doc/mpv/mpv.conf
vo=gpu-next
gpu-api=vulkan
hwdec=vulkan
gpu-context=waylandvk
# hwdec-codecs=all
# fs=no
# reload_key_binding=Ctrl+r
volume-max=100
volume=80
