-- https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tailwindcss
require("lspconfig").tailwindcss.setup({
	capabilities = require("capabilities"),
	on_attach = require("on_attach"),
	flags = require("flags"),
	-- filetypes = { "html", "pug", "css" },
	filetypes = {
		-- "aspnetcorerazor",
		-- "astro",
		-- "astro-markdown",
		-- "blade",
		-- "django-html",
		-- "edge",
		-- "eelixir",
		-- "ejs",
		-- "erb",
		-- "eruby",
		-- "gohtml",
		-- "haml",
		-- "handlebars",
		-- "hbs",
		"html",
		-- "html-eex",
		-- "jade",
		-- "leaf",
		-- "liquid",
		-- "markdown",
		-- "mdx",
		-- "mustache",
		-- "njk",
		-- "nunjucks",
		-- "php",
		-- "razor",
		-- "slim",
		-- "twig",
		"css",
		"less",
		"postcss",
		"sass",
		"scss",
		-- "stylus",
		-- "sugarss",
		-- "javascript",
		-- "javascriptreact",
		-- "reason",
		-- "rescript",
		"typescript",
		"typescriptreact",
		-- "vue",
		"svelte",
		-- "pug",
	},
	root_dir = require("lspconfig.util").root_pattern(
		"windi.config.ts",
		"tailwind.config.js",
		"tailwind.config.ts",
		"postcss.config.js",
		"postcss.config.ts",
		"package.json",
		"node_modules",
		".git"
	),
	settings = {
		-- https://github.com/tailwindlabs/tailwindcss-intellisense#extension-settings
		tailwindCSS = {
			emmetCompletions = true,
			classAttributes = {
				"class",
				"classWrap",
				"className",
				"classInput",
				"classText",
				"classAvatar",
				"classList",
			},
			lint = {
				cssConflict = "warning",
				invalidApply = "error",
				invalidConfigPath = "error",
				invalidScreen = "error",
				invalidTailwindDirective = "error",
				invalidVariant = "error",
				recommendedVariantOrder = "warning",
			},
			validate = true,
		},
	},
})
