follow_outside_symlinks "yes"
follow_inside_symlinks "yes"

# DSD # https://linuxtut.com/en/6455ad857fb48f0d4f36/

# https://mpd.readthedocs.io/en/latest/user.html#configuring-audio-outputs
audio_output {
	# https://mpd.readthedocs.io/en/latest/plugins.html#pipewire
	type "pipewire"
	name "pw_mpd_out"
	# dsd "yes"
}
# audio_output {
# 	# https://mpd.readthedocs.io/en/latest/plugins.html#alsa-plugin
#   type    "alsa"           
#   name    "alsa_mpd_out"  
# 	device "hw:0,0" # /proc/asound/cards # hw:name|number,0
#   mixer_type "software"  
# 	dop "yes"
# 	stop_dsd_silence "yes"
# }
# volume_normalization "yes"

# https://mpd.readthedocs.io/en/latest/plugins.html#playlist-plugins
playlist_plugin {
	name "m3u"
	enabled "false"
}

# https://mpd.readthedocs.io/en/latest/plugins.html#archive-plugins
# https://mpd.readthedocs.io/en/latest/plugins.html#decoder-plugins
