#!/bin/sh

if test "$DBUS_SESSION_BUS_ADDRESS" = ""; then
	eval "$(dbus-launch --exit-with-session --sh-syntax)"
fi
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
	dbus-update-activation-environment DISPLAY XAUTHORITY
fi

if [ "$(hostname)" = pc ]; then
	nvidia-settings -a '[gpu:0]/GPUFanControlState=1' -a '[fan:0]/GPUTargetFanSpeed=40' --load-config-only
	XDG_SESSION_TYPE=x11 remote-touchpad -bind :9000 -secret pc &
	systemctl --user start imwheel.service &
elif [ "$(hostname)" = dell ]; then
	systemctl --user restart blueman-applet.service &
	systemctl --user restart redshift.service &
fi
numlockx
xset r rate 250 50 s 3600
sxhkd -c "$SXHKDRC" &
systemctl --user restart dunst.service &
systemctl --user restart dwm-status.service &
systemctl --user restart unclutter-xfixes.service &
systemctl --user restart wallpaper.service &

session=${1:-dwm}
case $session in
i3 | i3wm) exec i3 ;;
kde) exec startplasma-x11 ;;
xfce | xfce4) exec startxfce4 ;;
dwm) exec dwm ;;
# Xephyr :0 -ac -br -noreset -screen 1152x720 & DISPLAY=:0.1 startx $XINITRC awesome
awesome) exec awesome -c /etc/nixos/awe/_rc.lua ;;
*) exec "$1" ;;
esac
