{ ... }:
{
  programs.lf = {
    enable = true;
    settings = {
      hidden = true;
      icons = true;
      ifs = "\n";
      info = "size";
      ratios = "1:2";
      scrolloff = 4;
      shell = "zsh";
      shellopts = "-ey";
    };
    commands = {
      get-mime-type = ''%xdg-mime query filetype "$f"'';
      open = "$$OPENER $f";
      touch = ''%touch "$@"'';
      mkdir = ''%mkdir "$@"'';
    };
    keybindings = {
      "." = "set hidden!";
      "<backspace>" = "set hidden!";
      H = "set hidden!";
      D = "%trash-put $fx";
      e = "$$EDITOR $fx";
      E = "$vim $fx";
      a = "push :touch<space>";
      A = "push :mkdir<space>";
      U = "!du -hs $fx";
      T = ":get-mime-type";
      "<esc>" = ":quit";
      ZZ = ":quit";
      "\\lg" = "!lazygit"; # not recognised
      "--" = "set ratios 1:2";
      "++" = "set ratios 1:2:3";
      "+w" = "$chmod +w $fx";
      "+x" = "$chmod +x $fx";
      "-w" = "$chmod -w $fx";
      "-x" = "$chmod -x $fx";
      "<c-f>" = "$fzf --preview 'pistol {}'";
      "<c-g>" = "$Rg";
      "gn" = ''$lf -remote "send $id cd /etc/nixos"'';
      "gx" = ''!xdg-open $fx'';
      "og" = ''&gimp $fx'';
      "of" = ''!firefox $fx'';
      "oz" = ''!zathura $fx'';
    };
    cmdKeybindings = { };
    extraConfig = ''
      $mkdir -p ~/.trash
      set previewer pistol
      map t
    '';
  };
  home.sessionVariables.LF_ICONS = ''
    tw=:\
    st=:\
    ow=:\
    dt=:\
    di=:\
    fi=:\
    ln=:\
    or=:\
    ex=:\
    *.c=:\
    *.cc=:\
    *.clj=:\
    *.coffee=:\
    *.cpp=:\
    *.css=:\
    *.d=:\
    *.dart=:\
    *.erl=:\
    *.exs=:\
    *.fs=:\
    *.go=:\
    *.h=:\
    *.hh=:\
    *.hpp=:\
    *.hs=:\
    *.html=:\
    *.java=:\
    *.jl=:\
    *.js=:\
    *.json=:\
    *.lua=:\
    *.md=:\
    *.php=:\
    *.pl=:\
    *.pro=:\
    *.py=:\
    *.rb=:\
    *.rs=:\
    *.scala=:\
    *.ts=:\
    *.vim=:\
    *.cmd=:\
    *.ps1=:\
    *.sh=:\
    *.bash=:\
    *.zsh=:\
    *.fish=:\
    *.tar=:\
    *.tgz=:\
    *.arc=:\
    *.arj=:\
    *.taz=:\
    *.lha=:\
    *.lz4=:\
    *.lzh=:\
    *.lzma=:\
    *.tlz=:\
    *.txz=:\
    *.tzo=:\
    *.t7z=:\
    *.zip=:\
    *.z=:\
    *.dz=:\
    *.gz=:\
    *.lrz=:\
    *.lz=:\
    *.lzo=:\
    *.xz=:\
    *.zst=:\
    *.tzst=:\
    *.bz2=:\
    *.bz=:\
    *.tbz=:\
    *.tbz2=:\
    *.tz=:\
    *.deb=:\
    *.rpm=:\
    *.jar=:\
    *.war=:\
    *.ear=:\
    *.sar=:\
    *.rar=:\
    *.alz=:\
    *.ace=:\
    *.zoo=:\
    *.cpio=:\
    *.7z=:\
    *.rz=:\
    *.cab=:\
    *.wim=:\
    *.swm=:\
    *.dwm=:\
    *.esd=:\
    *.jpg=:\
    *.jpeg=:\
    *.mjpg=:\
    *.mjpeg=:\
    *.gif=:\
    *.bmp=:\
    *.pbm=:\
    *.pgm=:\
    *.ppm=:\
    *.tga=:\
    *.xbm=:\
    *.xpm=:\
    *.tif=:\
    *.tiff=:\
    *.png=:\
    *.svg=:\
    *.svgz=:\
    *.mng=:\
    *.pcx=:\
    *.mov=:\
    *.mpg=:\
    *.mpeg=:\
    *.m2v=:\
    *.mkv=:\
    *.webm=:\
    *.ogm=:\
    *.mp4=:\
    *.m4v=:\
    *.mp4v=:\
    *.vob=:\
    *.qt=:\
    *.nuv=:\
    *.wmv=:\
    *.asf=:\
    *.rm=:\
    *.rmvb=:\
    *.flc=:\
    *.avi=:\
    *.fli=:\
    *.flv=:\
    *.gl=:\
    *.dl=:\
    *.xcf=:\
    *.xwd=:\
    *.yuv=:\
    *.cgm=:\
    *.emf=:\
    *.ogv=:\
    *.ogx=:\
    *.aac=:\
    *.au=:\
    *.flac=:\
    *.m4a=:\
    *.mid=:\
    *.midi=:\
    *.mka=:\
    *.mp3=:\
    *.mpc=:\
    *.ogg=:\
    *.ra=:\
    *.wav=:\
    *.oga=:\
    *.opus=:\
    *.spx=:\
    *.xspf=:\
    *.pdf=:\
    *.nix=:\
  '';
}
