# https://mpd.readthedocs.io/en/latest/user.html
# /run/mpd/mpd.conf
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
auto_update "yes"

audio_output {
	type "pipewire"
	name "pw_mpd_out"
}

playlist_plugin {
	name "m3u"
	enabled "yes"
    as_directory "yes"
}

decoder {
    # https://mpd.readthedocs.io/en/latest/plugins.html#decoder-ffmpeg
    plugin "ffmpeg"
    enabled  "yes"
}

# resampler {
#   plugin "soxr"
#   quality "very high"
# }
