#!/usr/bin/env bash

for ((COUNT = 1; COUNT <= 10; COUNT++)); do
	echo $COUNT
	# sleep 0.5
	sleep 1
done

exit 0

# while inotifywait -e modify /etc/nixos/_g/index.php; do
# 	echo someone touched my cheese
# done
