inode/directory eza --tree --level=3 --group --group-directories-first %pistol-filename%
text/* bat --color=always --style=plain --pager=never %pistol-filename%
application/json sh: jq '.' %pistol-filename% -C
application/pdf zathura %pistol-filename%
application/* bat --color=always --style=plain --pager=never %pistol-filename%
fpath .*.md$ sh: bat --paging=never --color=always %pistol-filename% | head -8
text/html w3m -T text/html -dump_source %pistol-filename%
image/svg\+xml inkview %pistol-filename%
image/* chafa %pistol-filename%
