image/x-xcursor bat %pistol-filename%
inode/directory eza --tree --level=3 --group --group-directories-first %pistol-filename%
text/* bat --color=always --style=plain --pager=never %pistol-filename%
application/vnd.sqlite3 sqlite3 %pistol-filename% .tables
application/json sh: jq '.' %pistol-filename% -C
application/pdf zathura %pistol-filename%
application/* bat --color=always --style=plain --pager=never %pistol-filename%
fpath .*.md$ sh: bat --paging=never --color=always %pistol-filename% | head -8
text/html w3m -T text/html -dump_source %pistol-filename%
image/* kitty +kitten icat --transfer-mode=stream %pistol-filename%
# https://sw.kovidgoyal.net/kitty/kittens/icat/
# image/* kitty +kitten icat --scale-up --transfer-mode=stream %pistol-filename%
# image/svg\+xml inkview %pistol-filename%
