memory_limit = 2G
; https://www.php.net/manual/en/ini.list.php
cli_server.color = 1
; https://xdebug.org/docs/all_settings#mode
xdebug.mode = off
; https://xdebug.org/docs/all_settings#start_with_request
xdebug.start_with_request = no
